### ISSUE TITLE
⚙️ Refactoring: refactoring of tests. Writing unit tests, integration tests, performance tests

### ISSUE THREAD

**Issue by Deemoguse** [Deemoguse/wambata-express-decorators#4]
**🤔 Why is it necessary?**
In order to be sure of the reliability of the library and its quality, more reliable tests should be introduced and developed. Among them:
- Unit tests;
- Integration tests;
- Performance tests.

**🛣️ Roadmap:**
- [x] Create unit tests;
- [ ] Create integration tests;
- [ ] Create performance tests.
